In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE A 1-D ARRAY USING array()

In [5]:
import numpy as np
a=np.array([1,2,3,])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# Create a 2-D array using array()

In [6]:
import numpy as np
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# Create a 2-D array using arange()

In [7]:
import numpy as np
b=np.arange(10).reshape(2,5)
print(b)
print(b.dtype)
print(b.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


In [9]:
import numpy as np
b=np.arange(10).reshape(5,2)
print(b)
print(b.dtype)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# Create a 3-D array using array()

In [10]:
import numpy as np
c=np.array(
    [[[1,2,3],[5,6,7]],
    [[8,9,10],[11,12,13]],
    [[14,15,16],[17,18,19]]]
)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]]
int32
(3, 2, 3)


# Create a 3-D array using arange()

In [12]:
import numpy as np
c=np.arange(1,19).reshape(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
int32
(3, 3, 2)


# Create array of ones(1-D)

In [13]:
import numpy as np
d=np.ones(2,dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[1 1]
int32
(2,)


# Create array of ones(1-D)

In [14]:
import numpy as np
d=np.ones(2,dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[1 1]
int32
(2,)


# Create array of ones(2-D)

In [15]:
import numpy as np
d=np.ones((2,3),dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# Create array of ones(3-D)

In [16]:
import numpy as np
d=np.ones((3,2,3),dtype="int32")
print(d)
print(d.dtype)
print(d.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# Create array of zeros(1-D)

In [17]:
import numpy as np
f=np.zeros((3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[0 0 0]
int32
(3,)


# Create array of Zeros(2-D)

In [18]:
import numpy as np
f=np.zeros((2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# Create array of Zeros(3-D)

In [19]:
import numpy as np
f=np.zeros((3,2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# Create an array with random numbers(1-D)

In [20]:
import numpy as np
a=np.random.randint(1,6,size=(6))
print(a)
print(a.dtype)
print(a.shape)

[5 5 1 5 5 3]
int32
(6,)


# Create a array with random numbers (2-D)

In [21]:
import numpy as np
b=np.random.randint(1,11,size=(2,3))
print(b)
print(b.dtype)
print(b.shape)

[[1 5 1]
 [8 2 5]]
int32
(2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [2]:
import numpy as np
c=np.random.randint(10,21,size=(3,2,3))
print(c)
print(c.dtype)
print(c.shape)

[[[18 19 17]
  [17 11 11]]

 [[17 12 12]
  [11 15 13]]

 [[10 12 18]
  [16 15 14]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [3]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 7 14  7]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [7]:
import numpy as np
b=np.random.randint([1,2,3],10)
print(b)
print(b.dtype)
print(b.shape)

[8 7 5]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [9]:
import numpy as np
a=np.random.randint([1,2,3,5],[10,20,30,40])
print(a)
print(a.dtype)
print(a.shape)

[ 5  6  5 16]
int32
(4,)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (1-D)

In [10]:
import numpy as np
a=np.random.randn(5)
print(a)
print(a.dtype)
print(a.shape)

[ 0.44591783 -0.77650648 -0.20552055 -1.06753294  0.48826949]
float64
(5,)


# CREATE NUMPY WITH RANDOM NUMBERS USING randn() (2-D)

In [13]:
import numpy as np
b=np.random.randn(3,2 )
print(b)
print(b.dtype)
print(b.shape)

[[ 0.76701371  0.10001411]
 [-0.70048219  2.76082006]
 [ 0.86130867  0.11109589]]
float64
(3, 2)


# CREATE NUMPY WITH RANDOM NUMBERS USING randn() (3-D)

In [15]:
import numpy as np
c=np.random.randn(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[-1.54924077  0.70815969]
  [ 0.51063348 -0.0108078 ]
  [ 0.25467343  0.00875369]]

 [[ 0.74016038  0.04215466]
  [ 0.63023595 -0.9986948 ]
  [-0.15025588 -0.60560691]]

 [[ 0.31457866  1.02417994]
  [ 0.63811037  1.18897236]
  [-0.65915678 -0.97153811]]]
float64
(3, 3, 2)


# CREATE ARRAY OF RANDOM NUMBERS USING rand()

In [16]:
import numpy as np
a=np.random.rand(5)
print(a)
print(a.dtype)
print(a.shape)

[0.81067646 0.46064345 0.27373711 0.34486574 0.81338228]
float64
(5,)


# POSITIVE INDEXING IN ARRAY(left - right)

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[7])
arr[3]

3
8
4


In [23]:
import numpy as np
arr=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arr[0,2])
print(arr[1,1])
print(arr[1,0])
print(arr[2,1])

3
6
5
9


In [24]:
import numpy as np
arr=np.array(
    [
        [[1,2,3],[4,5,6]],
        [[10,20,30],[12,13,14]],
        [[100,200,300],[400,500,600]]
    ])
print(arr[0,1,1])
print(arr[2,1,0])
print(arr[1,1,1])

5
400
13


# NEGETIVE INDEXING IN ARRAY(right - left)

In [25]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-2])
print(arr[-1])
print(arr[-7])

6
7
1


In [26]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])
print(arr[-2,-1])

5
3


In [28]:
import numpy as np
arr=np.array(
    [
        [[1,2,3],[5,6,7]],
        [[12,13,14],[11,10,49]]])
print(arr[-1,-1,-3])
print(arr[-2,-1,-3])

11
5


# MIXING OF (+ AND -)

In [31]:
import numpy as np
arr=np.array(
    [
        [[2,3,4],[5,6,7]],
        [[10,2,4],[6,7,29]],
        [[22,11,14],[23,45,44]]
    ]
)
print(arr[1,1,1])
print(arr[-2,-1,-2])
print(arr[2,-1,-2])
print(arr[-1,1,-2])

7
7
45
45


# NUMPY ARRAY SLICING

In [32]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [33]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [34]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGETIVE SLICING

In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])
print(arr[-6:-2])

[5 6]
[2 3 4 5]


In [36]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# SLICING 2-D ARRAYS

In [42]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [43]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

In [45]:
import numpy as np
arr = np.array([1,2,3,4,5])
a = arr.copy()
print("original array")
print(arr)
print("affected array")
arr[2] = 10
print(arr)
print(a)
a[0] = 20
print("affected array")
print(a)

original array
[1 2 3 4 5]
affected array
[ 1  2 10  4  5]
[1 2 3 4 5]
affected array
[20  2  3  4  5]


In [48]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
print("original array")
print(arr)
print("viewed array")
print(x)
print("affected array")
arr[0] = 30
print("arr : ",arr)
print(" x :",x)

original array
[1 2 3 4 5]
viewed array
[1 2 3 4 5]
affected array
arr :  [30  2  3  4  5]
 x : [30  2  3  4  5]


In [49]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("original array :",arr) 

original array : [ 1  2  3  4  5  6  7  8  9 10]


In [50]:
b = arr.reshape(5,2) 
print("2D array with shape 5x2")
print(b)

2D array with shape 5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [51]:
c = arr.reshape(2,5) 
print("2D array with shape 2x5")
print(c)

2D array with shape 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [55]:
d = arr.reshape(2,1,5)
print("3D array with shape 2,1,5")
print(d)

3D array with shape 2,1,5
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# AGREEGATION FUNCTIONS

In [57]:
import numpy as np
arr=np.array([1,2,3,4,5]) #1D
print("original 1D array : ",arr)
print(f"sum={np.sum(arr)}")
print()

original 1D array :  [1 2 3 4 5]
sum=15



In [58]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original 2D array : ",arr1)
print(f"sum={np.sum(arr1)}")
print()
arr2=np.array(
              [
               [[1,2,3],[4,5,6]],
               [[10,20,30],[40,50,60]]    
              ]
             )
print("original 3D array : ",arr2)
print(f"sum={np.sum(arr2)}")

original 2D array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
sum=55

original 3D array :  [[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
sum=231


In [59]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n:",arr)

print("Across Colswise") #column wise
print("sum =",np.sum(arr , axis=0))

print("Across Rowswise") #Row wise
print("sum =",np.sum(arr , axis=1))

original array 
: [[1 2 3 4]
 [5 6 7 8]]
Across Colswise
sum = [ 6  8 10 12]
Across Rowswise
sum = [10 26]


# mean() FUNCTION

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print("original array : ",arr)
print("mean : ",np.mean(arr))

original array :  [1 2 3 4 5 6 7 8]
mean :  4.5


In [61]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n: ",arr)

print("Across Rows") #column wise
print("Mean =",np.mean(arr , axis=0))

print("Across Columns") #Row wise
print("Mean =",np.mean(arr , axis=1))

original array 
:  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
Mean = [3. 4. 5. 6.]
Across Columns
Mean = [2.5 6.5]


In [63]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("standard div : ",np.std(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

standard div :  2.29128784747792


In [2]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array:",arr)
print("Across Rows")
print("std div=",np.std(arr,axis=0))
print()
print("Across columns")
print("std div=",np.std(arr,axis=1))

original array: [[1 2 3 4]
 [5 6 7 8]]
Across Rows
std div= [2. 2. 2. 2.]

Across columns
std div= [1.11803399 1.11803399]


# var() FUNCTION

In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("varients : ",np.var(arr))

original array :  [[1 2 3 4]
 [5 6 7 8]]

varients :  5.25


In [4]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array:",arr)
print("across rows")
print("var=",np.var(arr,axis=0))
print()
print("across column")
print("var=",np.var(arr,axis=1))

original array: [[1 2 3 4]
 [5 6 7 8]]
across rows
var= [4. 4. 4. 4.]

across column
var= [1.25 1.25]


# min(FUNCTION)

In [5]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("minimum : ",np.min(arr))

original array :  [[1 2 3 4]
 [5 6 7 8]]

minimum :  1


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array:",arr)
print("across rows")
print("min=",np.min(arr,axis=0))
print()
print("across columns")
print("min=",np.min(arr,axis=1))

original array: [[1 2 3 4]
 [5 6 7 8]]
across rows
min= [1 2 3 4]

across columns
min= [1 5]


# max() FUNCTION

In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("maximum : ",np.max(arr))

original array :  [[1 2 3 4]
 [5 6 7 8]]

maximum :  8


In [9]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("max =",np.max(arr , axis=0))
print()
print("Across Columns") #Row wise
print("max =",np.max(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
max = [5 6 7 8]

Across Columns
max = [4 8]
